# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657c1b3937ba63eff9058980ef0c15a61068da327020d3764e6463faafe4cbfd4532b2679617b7f441ae6535ed75448172fc17f286c268ca73bb6bbf2ac9d7bd

test:
  secret_key_base: 14edcff8a52da0f5cce83e18f25a24676b43aa25f5466a44b74a189e41e487e34265a3c702c265d9e4f7afa7e2a573aa21aecf5b57a57ce6d5a1dca8f52f0507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:  2f9c076bc01f46db9a62ea607241d1a1b64e0d565f8e2f75fba91e6942b8d721e8304d8c9464d9952f1ffb90c64d72c67ac4c3590c97ccbe75970a77a071ab43

